// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/network_connection.proto

#include "common/network_connection.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

static const ::_pb::EnumDescriptor* file_level_enum_descriptors_common_2fnetwork_5fconnection_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_common_2fnetwork_5fconnection_2eproto = nullptr;
const uint32_t TableStruct_common_2fnetwork_5fconnection_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_common_2fnetwork_5fconnection_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\037common/network_connection.proto\032 googl"
  "e/protobuf/descriptor.proto*\260M\n\033ENetwork"
  "DisconnectionReason\022\036\n\032NETWORK_DISCONNEC"
  "T_INVALID\020\000\022\037\n\033NETWORK_DISCONNECT_SHUTDO"
  "WN\020\001\022F\n%NETWORK_DISCONNECT_DISCONNECT_BY"
  "_USER\020\002\032\033\242\324\030\027#GameUI_Disconnect_User\022J\n\'"
  "NETWORK_DISCONNECT_DISCONNECT_BY_SERVER\020"
  "\003\032\035\242\324\030\031#GameUI_Disconnect_Server\022B\n\027NETW"
  "ORK_DISCONNECT_LOST\020\004\032%\242\324\030!#GameUI_Disco"
  "nnect_ConnectionLost\022J\n\033NETWORK_DISCONNE"
  "CT_OVERFLOW\020\005\032)\242\324\030%#GameUI_Disconnect_Co"
  "nnectionOverflow\022I\n\037NETWORK_DISCONNECT_S"
  "TEAM_BANNED\020\006\032$\242\324\030 #GameUI_Disconnect_St"
  "eamIDBanned\022G\n\036NETWORK_DISCONNECT_STEAM_"
  "INUSE\020\007\032#\242\324\030\037#GameUI_Disconnect_SteamIDI"
  "nUse\022G\n\037NETWORK_DISCONNECT_STEAM_TICKET\020"
  "\010\032\"\242\324\030\036#GameUI_Disconnect_SteamTicket\022E\n"
  "\036NETWORK_DISCONNECT_STEAM_LOGON\020\t\032!\242\324\030\035#"
  "GameUI_Disconnect_SteamLogon\022M\n&NETWORK_"
  "DISCONNECT_STEAM_AUTHCANCELLED\020\n\032!\242\324\030\035#G"
  "ameUI_Disconnect_SteamLogon\022O\n(NETWORK_D"
  "ISCONNECT_STEAM_AUTHALREADYUSED\020\013\032!\242\324\030\035#"
  "GameUI_Disconnect_SteamLogon\022K\n$NETWORK_"
  "DISCONNECT_STEAM_AUTHINVALID\020\014\032!\242\324\030\035#Gam"
  "eUI_Disconnect_SteamLogon\022M\n$NETWORK_DIS"
  "CONNECT_STEAM_VACBANSTATE\020\r\032#\242\324\030\033#GameUI"
  "_Disconnect_SteamVAC\260\324\030\000\022S\n,NETWORK_DISC"
  "ONNECT_STEAM_LOGGED_IN_ELSEWHERE\020\016\032!\242\324\030\035"
  "#GameUI_Disconnect_SteamInUse\022T\n+NETWORK"
  "_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT\020\017\032#"
  "\242\324\030\037#GameUI_Disconnect_SteamTimeOut\022I\n N"
  "ETWORK_DISCONNECT_STEAM_DROPPED\020\020\032#\242\324\030\037#"
  "GameUI_Disconnect_SteamDropped\022M\n\"NETWOR"
  "K_DISCONNECT_STEAM_OWNERSHIP\020\021\032%\242\324\030!#Gam"
  "eUI_Disconnect_SteamOwnership\022U\n&NETWORK"
  "_DISCONNECT_SERVERINFO_OVERFLOW\020\022\032)\242\324\030%#"
  "GameUI_Disconnect_ServerInfoOverflow\022K\n#"
  "NETWORK_DISCONNECT_TICKMSG_OVERFLOW\020\023\032\"\242"
  "\324\030\036#GameUI_Disconnect_TickMessage\022Y\n*NET"
  "WORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW\020"
  "\024\032)\242\324\030%#GameUI_Disconnect_StringTableMes"
  "sage\022S\n\'NETWORK_DISCONNECT_DELTAENTMSG_O"
  "VERFLOW\020\025\032&\242\324\030\"#GameUI_Disconnect_DeltaE"
  "ntMessage\022Q\n&NETWORK_DISCONNECT_TEMPENTM"
  "SG_OVERFLOW\020\026\032%\242\324\030!#GameUI_Disconnect_Te"
  "mpEntMessage\022O\n%NETWORK_DISCONNECT_SOUND"
  "SMSG_OVERFLOW\020\027\032$\242\324\030 #GameUI_Disconnect_"
  "SoundsMessage\022P\n#NETWORK_DISCONNECT_SNAP"
  "SHOTOVERFLOW\020\030\032\'\242\324\030##GameUI_Disconnect_S"
  "napshotOverflow\022J\n NETWORK_DISCONNECT_SN"
  "APSHOTERROR\020\031\032$\242\324\030 #GameUI_Disconnect_Sn"
  "apshotError\022P\n#NETWORK_DISCONNECT_RELIAB"
  "LEOVERFLOW\020\032\032\'\242\324\030##GameUI_Disconnect_Rel"
  "iableOverflow\022N\n\037NETWORK_DISCONNECT_BADD"
  "ELTATICK\020\033\032)\242\324\030%#GameUI_Disconnect_BadCl"
  "ientDeltaTick\022H\n\037NETWORK_DISCONNECT_NOMO"
  "RESPLITS\020\034\032#\242\324\030\037#GameUI_Disconnect_NoMor"
  "eSplits\022@\n\033NETWORK_DISCONNECT_TIMEDOUT\020\035"
  "\032\037\242\324\030\033#GameUI_Disconnect_TimedOut\022H\n\037NET"
  "WORK_DISCONNECT_DISCONNECTED\020\036\032#\242\324\030\037#Gam"
  "eUI_Disconnect_Disconnected\022H\n\037NETWORK_D"
  "ISCONNECT_LEAVINGSPLIT\020\037\032#\242\324\030\037#GameUI_Di"
  "sconnect_LeavingSplit\022X\n\'NETWORK_DISCONN"
  "ECT_DIFFERENTCLASSTABLES\020 \032+\242\324\030\'#GameUI_"
  "Disconnect_DifferentClassTables\022P\n#NETWO"
  "RK_DISCONNECT_BADRELAYPASSWORD\020!\032\'\242\324\030##G"
  "ameUI_Disconnect_BadRelayPassword\022X\n\'NET"
  "WORK_DISCONNECT_BADSPECTATORPASSWORD\020\"\032+"
  "\242\324\030\'#GameUI_Disconnect_BadSpectatorPassw"
  "ord\022L\n!NETWORK_DISCONNECT_HLTVRESTRICTED"
  "\020#\032%\242\324\030!#GameUI_Disconnect_HLTVRestricte"
  "d\022H\n\037NETWORK_DISCONNECT_NOSPECTATORS\020$\032#"
  "\242\324\030\037#GameUI_Disconnect_NoSpectators\022N\n\"N"
  "ETWORK_DISCONNECT_HLTVUNAVAILABLE\020%\032&\242\324\030"
  "\"#GameUI_Disconnect_HLTVUnavailable\022@\n\033N"
  "ETWORK_DISCONNECT_HLTVSTOP\020&\032\037\242\324\030\033#GameU"
  "I_Disconnect_HLTVStop\022<\n\031NETWORK_DISCONN"
  "ECT_KICKED\020\'\032\035\242\324\030\031#GameUI_Disconnect_Kic"
  "ked\022@\n\033NETWORK_DISCONNECT_BANADDED\020(\032\037\242\324"
  "\030\033#GameUI_Disconnect_BanAdded\022H\n\037NETWORK"
  "_DISCONNECT_KICKBANADDED\020)\032#\242\324\030\037#GameUI_"
  "Disconnect_KickBanAdded\022D\n\035NETWORK_DISCO"
  "NNECT_HLTVDIRECT\020*\032!\242\324\030\035#GameUI_Disconne"
  "ct_HLTVDirect\022\\\n)NETWORK_DISCONNECT_PURE"
  "SERVER_CLIENTEXTRA\020+\032-\242\324\030)#GameUI_Discon"
  "nect_PureServer_ClientExtra\022V\n&NETWORK_D"
  "ISCONNECT_PURESERVER_MISMATCH\020,\032*\242\324\030&#Ga"
  "meUI_Disconnect_PureServer_Mismatch\022>\n\032N"
  "ETWORK_DISCONNECT_USERCMD\020-\032\036\242\324\030\032#GameUI"
  "_Disconnect_UserCmd\022N\n#NETWORK_DISCONNEC"
  "T_REJECTED_BY_GAME\020.\032%\242\324\030!#GameUI_Discon"
  "nect_RejectedByGame\022T\n&NETWORK_DISCONNEC"
  "T_MESSAGE_PARSE_ERROR\020/\032(\242\324\030$#GameUI_Dis"
  "connect_MessageParseError\022X\n(NETWORK_DIS"
  "CONNECT_INVALID_MESSAGE_ERROR\0200\032*\242\324\030&#Ga"
  "meUI_Disconnect_InvalidMessageError\022T\n&N"
  "ETWORK_DISCONNECT_BAD_SERVER_PASSWORD\0201\032"
  "(\242\324\030$#GameUI_Disconnect_BadServerPasswor"
  "d\0221\n-NETWORK_DISCONNECT_DIRECT_CONNECT_R"
  "ESERVATION\0202\022S\n%NETWORK_DISCONNECT_CONNE"
  "CTION_FAILURE\0203\032(\242\324\030$#GameUI_Disconnect_"
  "ConnectionFailure\022Y\n)NETWORK_DISCONNECT_"
  "NO_PEER_GROUP_HANDLERS\0204\032*\242\324\030&#GameUI_Di"
  "sconnect_NoPeerGroupHandlers\022#\n\037NETWORK_"
  "DISCONNECT_RECONNECTION\0205\022H\n\037NETWORK_DIS"
  "CONNECT_LOOPSHUTDOWN\0206\032#\242\324\030\037#GameUI_Disc"
  "onnect_LoopShutdown\022L\n!NETWORK_DISCONNEC"
  "T_LOOPDEACTIVATE\0207\032%\242\324\030!#GameUI_Disconne"
  "ct_LoopDeactivate\022H\n\037NETWORK_DISCONNECT_"
  "HOST_ENDGAME\0208\032#\242\324\030\037#GameUI_Disconnect_H"
  "ost_EndGame\022\\\n*NETWORK_DISCONNECT_LOOP_L"
  "EVELLOAD_ACTIVATE\0209\032,\242\324\030(#GameUI_Disconn"
  "ect_LoopLevelLoadActivate\022V\n\'NETWORK_DIS"
  "CONNECT_CREATE_SERVER_FAILED\020:\032)\242\324\030%#Gam"
  "eUI_Disconnect_CreateServerFailed\022D\n\032NET"
  "WORK_DISCONNECT_EXITING\020;\032$\242\324\030 #GameUI_D"
  "isconnect_ExitingEngine\022T\n)NETWORK_DISCO"
  "NNECT_REQUEST_HOSTSTATE_IDLE\020<\032%\242\324\030!#Gam"
  "eUI_Disconnect_Request_HSIdle\022\\\n.NETWORK"
  "_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY\020"
  "=\032(\242\324\030$#GameUI_Disconnect_Request_HLTVRe"
  "lay\022Q\n*NETWORK_DISCONNECT_CLIENT_CONSIST"
  "ENCY_FAIL\020>\032!\242\324\030\035#GameUI_ClientConsisten"
  "cyFail\022Q\n+NETWORK_DISCONNECT_CLIENT_UNAB"
  "LE_TO_CRC_MAP\020\?\032 \242\324\030\034#GameUI_ClientUnabl"
  "eToCRCMap\022=\n NETWORK_DISCONNECT_CLIENT_N"
  "O_MAP\020@\032\027\242\324\030\023#GameUI_ClientNoMap\022K\n\'NETW"
  "ORK_DISCONNECT_CLIENT_DIFFERENT_MAP\020A\032\036\242"
  "\324\030\032#GameUI_ClientDifferentMap\022M\n(NETWORK"
  "_DISCONNECT_SERVER_REQUIRES_STEAM\020B\032\037\242\324\030"
  "\033#GameUI_ServerRequireSteams\022M\n\"NETWORK_"
  "DISCONNECT_STEAM_DENY_MISC\020C\032%\242\324\030!#GameU"
  "I_Disconnect_SteamDeny_Misc\022_\n,NETWORK_D"
  "ISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT\020D\032-\242"
  "\324\030)#GameUI_Disconnect_SteamDeny_BadAntiC"
  "heat\022M\n\"NETWORK_DISCONNECT_SERVER_SHUTDO"
  "WN\020E\032%\242\324\030!#GameUI_Disconnect_ServerShutd"
  "own\022U\n&NETWORK_DISCONNECT_REPLAY_INCOMPA"
  "TIBLE\020G\032)\242\324\030%#GameUI_Disconnect_ReplayIn"
  "compatible\022Z\n+NETWORK_DISCONNECT_CONNECT"
  "_REQUEST_TIMEDOUT\020H\032)\242\324\030%#GameUI_Disconn"
  "ect_ConnectionTimedout\022U\n&NETWORK_DISCON"
  "NECT_SERVER_INCOMPATIBLE\020I\032)\242\324\030%#GameUI_"
  "Disconnect_ServerIncompatible\022^\n*NETWORK"
  "_DISCONNECT_LOCALPROBLEM_MANYRELAYS\020J\032.\242"
  "\324\030*#GameUI_Disconnect_LocalProblem_ManyR"
  "elays\022z\n8NETWORK_DISCONNECT_LOCALPROBLEM"
  "_HOSTEDSERVERPRIMARYRELAY\020K\032<\242\324\0308#GameUI"
  "_Disconnect_LocalProblem_HostedServerPri"
  "maryRelay\022d\n-NETWORK_DISCONNECT_LOCALPRO"
  "BLEM_NETWORKCONFIG\020L\0321\242\324\030-#GameUI_Discon"
  "nect_LocalProblem_NetworkConfig\022T\n%NETWO"
  "RK_DISCONNECT_LOCALPROBLEM_OTHER\020M\032)\242\324\030%"
  "#GameUI_Disconnect_LocalProblem_Other\022S\n"
  "!NETWORK_DISCONNECT_REMOTE_TIMEOUT\020O\032,\242\324"
  "\030(#GameUI_Disconnect_RemoteProblem_Timeo"
  "ut\022h\n,NETWORK_DISCONNECT_REMOTE_TIMEOUT_"
  "CONNECTING\020P\0326\242\324\0302#GameUI_Disconnect_Rem"
  "oteProblem_TimeoutConnecting\022O\n\037NETWORK_"
  "DISCONNECT_REMOTE_OTHER\020Q\032*\242\324\030&#GameUI_D"
  "isconnect_RemoteProblem_Other\022U\n\"NETWORK"
  "_DISCONNECT_REMOTE_BADCRYPT\020R\032-\242\324\030)#Game"
  "UI_Disconnect_RemoteProblem_BadCrypt\022Z\n("
  "NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED"
  "\020S\032,\242\324\030(#GameUI_Disconnect_RemoteProblem"
  "_BadCert\022>\n\032NETWORK_DISCONNECT_UNUSUAL\020T"
  "\032\036\242\324\030\032#GameUI_Disconnect_Unusual\022K\n!NETW"
  "ORK_DISCONNECT_INTERNAL_ERROR\020U\032$\242\324\030 #Ga"
  "meUI_Disconnect_InternalError\022Q\n&NETWORK"
  "_DISCONNECT_REJECT_BADCHALLENGE\020\200\001\032$\242\324\030 "
  "#GameUI_ServerRejectBadChallenge\022A\n!NETW"
  "ORK_DISCONNECT_REJECT_NOLOBBY\020\201\001\032\031\242\324\030\025#G"
  "ameUI_ServerNoLobby\022O\n(NETWORK_DISCONNEC"
  "T_REJECT_BACKGROUND_MAP\020\202\001\032 \242\324\030\034#Valve_R"
  "eject_Background_Map\022M\n\'NETWORK_DISCONNE"
  "CT_REJECT_SINGLE_PLAYER\020\203\001\032\037\242\324\030\033#Valve_R"
  "eject_Single_Player\022I\n%NETWORK_DISCONNEC"
  "T_REJECT_HIDDEN_GAME\020\204\001\032\035\242\324\030\031#Valve_Reje"
  "ct_Hidden_Game\022O\n%NETWORK_DISCONNECT_REJ"
  "ECT_LANRESTRICT\020\205\001\032#\242\324\030\037#GameUI_ServerRe"
  "jectLANRestrict\022O\n%NETWORK_DISCONNECT_RE"
  "JECT_BADPASSWORD\020\206\001\032#\242\324\030\037#GameUI_ServerR"
  "ejectBadPassword\022M\n$NETWORK_DISCONNECT_R"
  "EJECT_SERVERFULL\020\207\001\032\"\242\324\030\036#GameUI_ServerR"
  "ejectServerFull\022]\n,NETWORK_DISCONNECT_RE"
  "JECT_INVALIDRESERVATION\020\210\001\032*\242\324\030&#GameUI_"
  "ServerRejectInvalidReservation\022S\n\'NETWOR"
  "K_DISCONNECT_REJECT_FAILEDCHANNEL\020\211\001\032%\242\324"
  "\030!#GameUI_ServerRejectFailedChannel\022W\n,N"
  "ETWORK_DISCONNECT_REJECT_CONNECT_FROM_LO"
  "BBY\020\212\001\032$\242\324\030 #Valve_Reject_Connect_From_L"
  "obby\022W\n,NETWORK_DISCONNECT_REJECT_RESERV"
  "ED_FOR_LOBBY\020\213\001\032$\242\324\030 #Valve_Reject_Reser"
  "ved_For_Lobby\022Z\n*NETWORK_DISCONNECT_REJE"
  "CT_INVALIDKEYLENGTH\020\214\001\032)\242\324\030%#GameUI_Serv"
  "erReject_InvalidKeyLength\022O\n%NETWORK_DIS"
  "CONNECT_REJECT_OLDPROTOCOL\020\215\001\032#\242\324\030\037#Game"
  "UI_ServerRejectOldProtocol\022O\n%NETWORK_DI"
  "SCONNECT_REJECT_NEWPROTOCOL\020\216\001\032#\242\324\030\037#Gam"
  "eUI_ServerRejectNewProtocol\022[\n+NETWORK_D"
  "ISCONNECT_REJECT_INVALIDCONNECTION\020\217\001\032)\242"
  "\324\030%#GameUI_ServerRejectInvalidConnection"
  "\022U\n(NETWORK_DISCONNECT_REJECT_INVALIDCER"
  "TLEN\020\220\001\032&\242\324\030\"#GameUI_ServerRejectInvalid"
  "CertLen\022_\n-NETWORK_DISCONNECT_REJECT_INV"
  "ALIDSTEAMCERTLEN\020\221\001\032+\242\324\030\'#GameUI_ServerR"
  "ejectInvalidSteamCertLen\022C\n\037NETWORK_DISC"
  "ONNECT_REJECT_STEAM\020\222\001\032\035\242\324\030\031#GameUI_Serv"
  "erRejectSteam\022Q\n,NETWORK_DISCONNECT_REJE"
  "CT_SERVERAUTHDISABLED\020\223\001\032\036\242\324\030\032#GameUI_Se"
  "rverAuthDisabled\022Y\n0NETWORK_DISCONNECT_R"
  "EJECT_SERVERCDKEYAUTHINVALID\020\224\001\032\"\242\324\030\036#Ga"
  "meUI_ServerCDKeyAuthInvalid\022E\n NETWORK_D"
  "ISCONNECT_REJECT_BANNED\020\225\001\032\036\242\324\030\032#GameUI_"
  "ServerRejectBanned\022T\n%NETWORK_DISCONNECT"
  "_KICKED_TEAMKILLING\020\226\001\032(\242\324\030$#Player_Disc"
  "onnectReason_TeamKilling\022N\n\"NETWORK_DISC"
  "ONNECT_KICKED_TK_START\020\227\001\032%\242\324\030!#Player_D"
  "isconnectReason_TK_Start\022^\n*NETWORK_DISC"
  "ONNECT_KICKED_UNTRUSTEDACCOUNT\020\230\001\032-\242\324\030)#"
  "Player_DisconnectReason_UntrustedAccount"
  "\022^\n*NETWORK_DISCONNECT_KICKED_CONVICTEDA"
  "CCOUNT\020\231\001\032-\242\324\030)#Player_DisconnectReason_"
  "ConvictedAccount\022d\n-NETWORK_DISCONNECT_K"
  "ICKED_COMPETITIVECOOLDOWN\020\232\001\0320\242\324\030,#Playe"
  "r_DisconnectReason_CompetitiveCooldown\022T"
  "\n%NETWORK_DISCONNECT_KICKED_TEAMHURTING\020"
  "\233\001\032(\242\324\030$#Player_DisconnectReason_TeamHur"
  "ting\022Z\n(NETWORK_DISCONNECT_KICKED_HOSTAG"
  "EKILLING\020\234\001\032+\242\324\030\'#Player_DisconnectReaso"
  "n_HostageKilling\022N\n\"NETWORK_DISCONNECT_K"
  "ICKED_VOTEDOFF\020\235\001\032%\242\324\030!#Player_Disconnec"
  "tReason_VotedOff\022F\n\036NETWORK_DISCONNECT_K"
  "ICKED_IDLE\020\236\001\032!\242\324\030\035#Player_DisconnectRea"
  "son_Idle\022L\n!NETWORK_DISCONNECT_KICKED_SU"
  "ICIDE\020\237\001\032$\242\324\030 #Player_DisconnectReason_S"
  "uicide\022V\n&NETWORK_DISCONNECT_KICKED_NOST"
  "EAMLOGIN\020\240\001\032)\242\324\030%#Player_DisconnectReaso"
  "n_NoSteamLogin\022X\n\'NETWORK_DISCONNECT_KIC"
  "KED_NOSTEAMTICKET\020\241\001\032*\242\324\030&#Player_Discon"
  "nectReason_NoSteamTicket\022\217\001\n)NETWORK_DIS"
  "CONNECT_KICKED_INPUTAUTOMATION\020\242\001\032_\242\324\030(#"
  "Player_DisconnectReason_InputAutomation\252"
  "\324\030/#Player_DisconnectReason_InputAutomat"
  "ion_Detail\022n\n0NETWORK_DISCONNECT_KICKED_"
  "VACNETABNORMALBEHAVIOR\020\243\001\0327\242\324\030/#Player_D"
  "isconnectReason_VacNetAbnormalBehavior\260\324"
  "\030\000\022Z\n(NETWORK_DISCONNECT_KICKED_INSECURE"
  "CLIENT\020\244\001\032+\242\324\030\'#Player_DisconnectReason_"
  "InsecureClient:E\n\030network_connection_tok"
  "en\022!.google.protobuf.EnumValueOptions\030\304\212"
  "\003 \001(\t:L\n\037network_connection_detail_token"
  "\022!.google.protobuf.EnumValueOptions\030\305\212\003 "
  "\001(\t:F\n\023allowed_from_client\022!.google.prot"
  "obuf.EnumValueOptions\030\306\212\003 \001(\010:\004true"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_common_2fnetwork_5fconnection_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::_pbi::once_flag descriptor_table_common_2fnetwork_5fconnection_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_common_2fnetwork_5fconnection_2eproto = {
    false, false, 10195, descriptor_table_protodef_common_2fnetwork_5fconnection_2eproto,
    "common/network_connection.proto",
    &descriptor_table_common_2fnetwork_5fconnection_2eproto_once, descriptor_table_common_2fnetwork_5fconnection_2eproto_deps, 1, 0,
    schemas, file_default_instances, TableStruct_common_2fnetwork_5fconnection_2eproto::offsets,
    nullptr, file_level_enum_descriptors_common_2fnetwork_5fconnection_2eproto,
    file_level_service_descriptors_common_2fnetwork_5fconnection_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_common_2fnetwork_5fconnection_2eproto_getter() {
  return &descriptor_table_common_2fnetwork_5fconnection_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_common_2fnetwork_5fconnection_2eproto(&descriptor_table_common_2fnetwork_5fconnection_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ENetworkDisconnectionReason_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_common_2fnetwork_5fconnection_2eproto);
  return file_level_enum_descriptors_common_2fnetwork_5fconnection_2eproto[0];
}
bool ENetworkDisconnectionReason_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
    case 31:
    case 32:
    case 33:
    case 34:
    case 35:
    case 36:
    case 37:
    case 38:
    case 39:
    case 40:
    case 41:
    case 42:
    case 43:
    case 44:
    case 45:
    case 46:
    case 47:
    case 48:
    case 49:
    case 50:
    case 51:
    case 52:
    case 53:
    case 54:
    case 55:
    case 56:
    case 57:
    case 58:
    case 59:
    case 60:
    case 61:
    case 62:
    case 63:
    case 64:
    case 65:
    case 66:
    case 67:
    case 68:
    case 69:
    case 71:
    case 72:
    case 73:
    case 74:
    case 75:
    case 76:
    case 77:
    case 79:
    case 80:
    case 81:
    case 82:
    case 83:
    case 84:
    case 85:
    case 128:
    case 129:
    case 130:
    case 131:
    case 132:
    case 133:
    case 134:
    case 135:
    case 136:
    case 137:
    case 138:
    case 139:
    case 140:
    case 141:
    case 142:
    case 143:
    case 144:
    case 145:
    case 146:
    case 147:
    case 148:
    case 149:
    case 150:
    case 151:
    case 152:
    case 153:
    case 154:
    case 155:
    case 156:
    case 157:
    case 158:
    case 159:
    case 160:
    case 161:
    case 162:
    case 163:
    case 164:
      return true;
    default:
      return false;
  }
}

const std::string network_connection_token_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::EnumValueOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  network_connection_token(kNetworkConnectionTokenFieldNumber, network_connection_token_default, nullptr);
const std::string network_connection_detail_token_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::EnumValueOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  network_connection_detail_token(kNetworkConnectionDetailTokenFieldNumber, network_connection_detail_token_default, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::EnumValueOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false>
  allowed_from_client(kAllowedFromClientFieldNumber, true, nullptr);

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
